### ISSUE TITLE
打卡也要内网了😓有办法加个webvpn代理之类的吗

### ISSUE THREAD

**Issue by nianjutu** [Long0x0/ZJU-nCov-Hitcarder-Sample#1]

**Comment by Long0x0** [comment]
应该只是暂时的，现在已经恢复了
webvpn也正在[dev分支](/Long0x0/ZJU-nCov-Hitcarder/tree/dev)部署，如果不行的话就会上线

**Comment by mrrubiks** [comment]
应该不可能内网打卡，不让离校了就没办法了
