### ISSUE TITLE
微信和钉钉机器人推送失效

### ISSUE THREAD

**Issue by zafirshi** [Long0x0/ZJU-nCov-Hitcarder-Sample#11]
rt，最近在使用时，发现GitHub action中显示自动打卡成功，但钉钉机器人和微信推送消息不知怎么的失效了，

是我这边自己的问题吗？求教大佬！

最后，感谢您的项目，真的省心又方便！

**Comment by Long0x0** [comment]
钉钉的问题 #6 可以换个时间试试
微信pushplus似乎已经失效，我再确认一下

**Comment by zafirshi** [comment]
感谢！问题已解决！
