### ISSUE TITLE
手动定位功能被关闭，打卡失败

### ISSUE THREAD

**Issue by qq854372571** [Long0x0/ZJU-nCov-Hitcarder-Sample#12]
今天开始手动定位功能被关闭了，然后钉钉打卡机器人提示：打卡信息已改变，请手动打卡，这个问题有解决办法吗

**Comment by Long0x0** [comment]
暂时没时间改，先自己手动打卡吧

**Comment by Long0x0** [comment]
已更新 https://github.com/Long0x0/ZJU-nCov-Hitcarder/pull/3 https://github.com/Long0x0/ZJU-nCov-Hitcarder/commit/d373347be67f83c50f69830f892baccbd8949619
